#!/bin/bash
# Check for newer versions of all pinned tools in tool-versions.env.
# Outputs a Markdown report of tools with available updates.
# Exit code 0 = updates found, 1 = no updates or error.

set -euo pipefail

VERSIONS_FILE="${1:-sources/install/tool-versions.env}"
REPORT=""
UPDATE_COUNT=0
ERROR_COUNT=0

fetch_latest() {
  local datasource="$1" dep_name="$2"
  case "$datasource" in
    github-releases)
      curl -sf --max-time 10 \
        -H "Accept: application/vnd.github+json" \
        ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} \
        "https://api.github.com/repos/${dep_name}/releases/latest" \
        | jq -r '.tag_name // empty' 2>/dev/null
      ;;
    github-tags)
      curl -sf --max-time 10 \
        -H "Accept: application/vnd.github+json" \
        ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} \
        "https://api.github.com/repos/${dep_name}/tags?per_page=1" \
        | jq -r '.[0].name // empty' 2>/dev/null
      ;;
    pypi)
      curl -sf --max-time 10 \
        "https://pypi.org/pypi/${dep_name}/json" \
        | jq -r '.info.version // empty' 2>/dev/null
      ;;
    rubygems)
      curl -sf --max-time 10 \
        "https://rubygems.org/api/v1/gems/${dep_name}.json" \
        | jq -r '.version // empty' 2>/dev/null
      ;;
    npm)
      curl -sf --max-time 10 \
        "https://registry.npmjs.org/${dep_name}/latest" \
        | jq -r '.version // empty' 2>/dev/null
      ;;
    crate)
      curl -sf --max-time 10 \
        "https://crates.io/api/v1/crates/${dep_name}" \
        -H "User-Agent: exegol-version-check" \
        | jq -r '.crate.max_stable_version // .crate.max_version // empty' 2>/dev/null
      ;;
    *)
      echo ""
      ;;
  esac
}

normalize_version() {
  # Strip leading 'v' for comparison
  echo "${1#v}"
}

echo "Checking tool versions..." >&2

datasource=""
dep_name=""

while IFS= read -r line; do
  # Parse renovate annotation
  if [[ "$line" =~ ^#\ renovate:\ datasource=([^ ]+)\ depName=(.+)$ ]]; then
    datasource="${BASH_REMATCH[1]}"
    dep_name="${BASH_REMATCH[2]}"
    continue
  fi

  # Parse version variable
  if [[ -n "$datasource" && "$line" =~ ^([A-Z0-9_]+_VERSION)=\"([^\"]+)\"$ ]]; then
    var_name="${BASH_REMATCH[1]}"
    current="${BASH_REMATCH[2]}"

    echo -n "  ${dep_name} ... " >&2
    latest=$(fetch_latest "$datasource" "$dep_name" || true)

    if [[ -z "$latest" ]]; then
      echo "failed to fetch" >&2
      ERROR_COUNT=$((ERROR_COUNT + 1))
      datasource=""
      dep_name=""
      continue
    fi

    current_norm=$(normalize_version "$current")
    latest_norm=$(normalize_version "$latest")

    if [[ "$current_norm" != "$latest_norm" ]]; then
      echo "${current} -> ${latest}" >&2
      REPORT="${REPORT}| ${dep_name} | ${datasource} | ${current} | ${latest} |\n"
      UPDATE_COUNT=$((UPDATE_COUNT + 1))
    else
      echo "up to date (${current})" >&2
    fi

    datasource=""
    dep_name=""
  fi
done < "$VERSIONS_FILE"

echo "" >&2
echo "Done: ${UPDATE_COUNT} updates, ${ERROR_COUNT} errors" >&2

if [[ "$UPDATE_COUNT" -eq 0 ]]; then
  echo "All tools are up to date."
  exit 1
fi

# Build Markdown report
cat <<EOF
## Tool Version Updates Available

**${UPDATE_COUNT}** tool(s) have newer versions available.
$(if (( ERROR_COUNT > 0 )); then echo "*${ERROR_COUNT} tool(s) failed to check.*"; fi)

| Tool | Source | Current | Latest |
|------|--------|---------|--------|
$(echo -e "$REPORT")

> Auto-generated by [check-tool-versions](.github/scripts/check-tool-versions.sh) workflow.
EOF
exit 0
